Task4 Task5
IT-Prospects/business-calendar-backend pull request #14
Opened 2023-10-11 18:42 UTC by putilove

https://github.com/IT-Prospects/business-calendar-backend/issues/4
https://github.com/IT-Prospects/business-calendar-backend/issues/5

2023-10-11 22:14 UTC, prafdin requested changes
1. Почему два класса EventDTO в разных проектах?
2.  BussinesCalendar.sln в корне проекта не открывает проект, а тот что в папке работает норм.
3. В проекте 1Model у каких-то моделей есть два конструктора: с параметрами и без параметров. В Image у конструктора для стринги не сетится пустая строка, а в City сетится - приведи всё в один вид. (а разве стринга не пустая поумолчанию?)
4. Если используешь Type? нотацию, то включи для всех проектов Nullable типы. 
5. Если класс сгенерирован, то оставь соответсвующий коммент в 1 строке файла класса.

2023-10-12 21:41 UTC, putilove commented on DAL/Event/EventDAO.cs
> +                    return DbSet.Where(x => x.EventDate.Date == param.TargetDate.Value.Date).Skip(param.Offset ?? 0).Take(6).ToList();
Своеобразно исправил

2023-10-12 21:41 UTC, putilove commented on BusinessCalendar/Program.cs
> +            app.UseHttpsRedirection();
Убрал

2023-10-12 21:41 UTC, putilove commented on BusinessCalendar/Program.cs
> +                RequestPath = "/images"
Исправил

2023-10-12 21:41 UTC, putilove commented on BusinessCalendar/Program.cs
> +                    ConfigurationHelper.GetString("serverName"),
Переименовал

2023-10-14 04:26 UTC, prafdin requested changes
1. Давай переведем русский текст на английский для избежания проблем с кодировкой.

2023-10-14 04:26 UTC, prafdin commented on Model/Event/Event.cs
> +        public long Image_Id { get; set; }
```suggestion
        public long Image_Id { get => Image.Id ; set => Image.Id = value; }
```
Можем так сделать? Если да, то поправь остальные связанные места в классе

2023-10-14 04:26 UTC, prafdin commented on DAL/Common/ConfigurationHelper.cs
> +        private static IConfiguration _configuration;
Visual Studio тут ругается следующим ворнингом 
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8618	Non-nullable field '_configuration' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.	2DAL	C:\Users\ivpr0122\Documents\Personal\business-calendar-backend\DAL\Common\ConfigurationHelper.cs	8	Active
```
я с ней согласен.

2023-10-14 04:26 UTC, prafdin commented on DAL/Common/ConfigurationHelper.cs
> +        private static readonly string _invalidFormatMessage = "При попытке преобразовать значение {0} произошла ошибка";
Давай переведем на английский.

2023-10-14 04:26 UTC, prafdin commented on DAL/Common/UnitOfWork.cs
> +                _context = null;
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8625	Cannot convert null literal to non-nullable reference type.	2DAL	C:\Users\ivpr0122\Documents\Personal\business-calendar-backend\DAL\Common\UnitOfWork.cs	60	Active
```

2023-10-14 04:26 UTC, prafdin commented on DAL/Event/EventDAO.cs
> +                    return DbSet.Where(x => x.EventDate.Date == param.TargetDate.Value.Date).Skip(param.Offset ?? 0).Take(6).ToList();
нормально!

2023-10-19 11:59 UTC, merged